/*\
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

//import Controller.UserController;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author prajeetajoshi
 */
public class AdminPersonalInfo extends javax.swing.JFrame {

    /**
     * Creates new form AdminPersonalInfo
     */
    public AdminPersonalInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstName = new javax.swing.JLabel();
        ContactNumber = new javax.swing.JLabel();
        IdentificationNumber = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        savebutton = new javax.swing.JButton();
        firstname = new javax.swing.JTextField();
        contactno = new javax.swing.JTextField();
        idnum = new javax.swing.JTextField();
        emailaddress = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        AdminIdLabel = new javax.swing.JLabel();
        adminid = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        adminusername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        HeadingLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FirstName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        FirstName.setText("First Name:");
        getContentPane().add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        ContactNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ContactNumber.setText("Contact Number:");
        getContentPane().add(ContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        IdentificationNumber.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        IdentificationNumber.setText("Identification Number:");
        getContentPane().add(IdentificationNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        Email.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Email.setText("Email:");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        LastName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        LastName.setText("Last Name:");
        getContentPane().add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        Address.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Address.setText("Address:");
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        savebutton.setBackground(new java.awt.Color(38, 79, 201));
        savebutton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        savebutton.setForeground(new java.awt.Color(255, 255, 255));
        savebutton.setText("Save");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(savebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 120, 40));

        firstname.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        firstname.setForeground(new java.awt.Color(216, 216, 216));
        firstname.setText("First Name");
        firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameFocusLost(evt);
            }
        });
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        getContentPane().add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 190, 40));

        contactno.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        contactno.setForeground(new java.awt.Color(216, 216, 216));
        contactno.setText("Contact Number");
        contactno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactnoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactnoFocusLost(evt);
            }
        });
        getContentPane().add(contactno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 670, 40));

        idnum.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        idnum.setForeground(new java.awt.Color(216, 216, 216));
        idnum.setText("Provide your citizenship/National Id");
        idnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idnumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idnumFocusLost(evt);
            }
        });
        getContentPane().add(idnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 670, 40));

        emailaddress.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        emailaddress.setForeground(new java.awt.Color(216, 216, 216));
        emailaddress.setText("Provide your email address");
        emailaddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailaddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailaddressFocusLost(evt);
            }
        });
        getContentPane().add(emailaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 670, 40));

        lastname.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lastname.setForeground(new java.awt.Color(216, 216, 216));
        lastname.setText("Last Name");
        lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameFocusLost(evt);
            }
        });
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        getContentPane().add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 210, 40));

        address.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        address.setForeground(new java.awt.Color(216, 216, 216));
        address.setText("Your address");
        address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFocusLost(evt);
            }
        });
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 670, 40));

        AdminIdLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        AdminIdLabel.setText("Admin Id:");
        getContentPane().add(AdminIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        adminid.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        adminid.setForeground(new java.awt.Color(216, 216, 216));
        adminid.setText("Admin Id");
        adminid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adminidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                adminidFocusLost(evt);
            }
        });
        adminid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminidActionPerformed(evt);
            }
        });
        getContentPane().add(adminid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 190, 40));

        UsernameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        UsernameLabel.setText("Admin Username:");
        getContentPane().add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        adminusername.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        adminusername.setForeground(new java.awt.Color(216, 216, 216));
        adminusername.setText("Username");
        adminusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adminusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                adminusernameFocusLost(evt);
            }
        });
        getContentPane().add(adminusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bng.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 980, 590));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 980, 580));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        HeadingLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        HeadingLabel.setText("Personal Information");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2025-05-22 at 20.45.48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(262, 262, 262)
                .addComponent(HeadingLabel)
                .addContainerGap(388, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(HeadingLabel)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        // TODO add your handling code here:
        String f_name = firstname.getText().trim();   //trim removes the unnecessary spaces
        String s_name = lastname.getText().trim();
        String email = emailaddress.getText().trim();
        String admin_username = adminusername.getText().trim();
        String contact_number = contactno.getText().trim();
        String admin_id = adminid.getText().trim();
        String admin_address = address.getText().trim();
        String id_number = idnum.getText().trim();

//        UserController controller = new UserController();
//    String result = controller.register(f_name, s_name, email, admin_username, contact_number, admin_id, admin_address, id_number);
//    JOptionPane.showMessageDialog(this, result);
    }//GEN-LAST:event_savebuttonActionPerformed

    private void firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusGained
        // TODO add your handling code here:
        if (firstname.getText().equals("First Name")){
            firstname.setText("");
            firstname.setForeground(Color.BLACK);
       
        } 
    }//GEN-LAST:event_firstnameFocusGained

    private void firstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusLost
        // TODO add your handling code here:
        if(firstname.getText().isEmpty()){
            firstname.setText("First Name");
            firstname.setForeground(new java.awt.Color(216,216,216));
        
           
        } 
    }//GEN-LAST:event_firstnameFocusLost

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void contactnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactnoFocusGained
        // TODO add your handling code here:
        if (contactno.getText().equals("Contact Number")){
            contactno.setText("");
            contactno.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_contactnoFocusGained

    private void contactnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactnoFocusLost
        // TODO add your handling code here:
        if(contactno.getText().isEmpty()){
            contactno.setText("Contact Number");
            contactno.setForeground(new java.awt.Color(216,216,216));
        }
    }//GEN-LAST:event_contactnoFocusLost

    private void idnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idnumFocusGained
        // TODO add your handling code here:
        if (idnum.getText().equals("Provide your citizenship/National Id")){
            idnum.setText("");
            idnum.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_idnumFocusGained

    private void idnumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idnumFocusLost
        // TODO add your handling code here:
        if ( idnum.getText().isEmpty()){
            idnum.setText("Provide your citizenship/National Id");
            idnum.setForeground(new java.awt.Color(216,216,216));
        }
    }//GEN-LAST:event_idnumFocusLost

    private void emailaddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailaddressFocusGained
        // TODO add your handling code here:
        if (emailaddress.getText().equals("Provide your email address")){
            emailaddress.setText("");
            emailaddress.setForeground(Color.BLACK);
        }

    }//GEN-LAST:event_emailaddressFocusGained

    private void emailaddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailaddressFocusLost
        // TODO add your handling code here:
        if (emailaddress.getText().isEmpty()){
            emailaddress.setText("Provide your email address");
            emailaddress.setForeground(new java.awt.Color(216,216,216));
        }
    }//GEN-LAST:event_emailaddressFocusLost

    private void lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusGained
        // TODO add your handling code here:
        if (lastname.getText().equals("Last Name")){
            lastname.setText("");
            lastname.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_lastnameFocusGained

    private void lastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusLost
        // TODO add your handling code here:
        if(lastname.getText().isEmpty()){
            lastname.setText("Last Name");
            lastname.setForeground(new java.awt.Color(216,216,216));
        }
    }//GEN-LAST:event_lastnameFocusLost

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusGained
        // TODO add your handling code here:
        if (address.getText().equals("Your address")){
            address.setText("");
            address.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_addressFocusGained

    private void addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusLost
        // TODO add your handling code here:
        if (address.getText().isEmpty()){
            address.setText("Your address");
            address.setForeground(new java.awt.Color(216,216,216));
        }

    }//GEN-LAST:event_addressFocusLost

    private void adminidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adminidFocusGained
        // TODO add your handling code here:
        if (adminid.getText().equals("Admin Id")){
            adminid.setText("");
            adminid.setForeground(Color.BLACK);
        }

    }//GEN-LAST:event_adminidFocusGained

    private void adminidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adminidFocusLost
        // TODO add your handling code here:
        if (adminid.getText().isEmpty()){
            adminid.setText("Admin Id");
            adminid.setForeground(new java.awt.Color(216,216,216));
        }
    }//GEN-LAST:event_adminidFocusLost

    private void adminidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminidActionPerformed

    private void adminusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adminusernameFocusGained
        // TODO add your handling code here:
        if (adminusername.getText().equals("Username")){
            adminusername.setText("");
            adminusername.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_adminusernameFocusGained

    private void adminusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adminusernameFocusLost
        // TODO add your handling code here:
        if ( adminusername.getText().isEmpty()){
            adminusername.setText("Username");
            adminusername.setForeground(new java.awt.Color(216,216,216));
        }

    }//GEN-LAST:event_adminusernameFocusLost

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
    
                            
    }//GEN-LAST:event_EditButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPersonalInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel AdminIdLabel;
    private javax.swing.JLabel ContactNumber;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JLabel IdentificationNumber;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField address;
    private javax.swing.JTextField adminid;
    private javax.swing.JTextField adminusername;
    private javax.swing.JTextField contactno;
    private javax.swing.JTextField emailaddress;
    private javax.swing.JTextField firstname;
    private javax.swing.JTextField idnum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastname;
    private javax.swing.JButton savebutton;
    // End of variables declaration//GEN-END:variables
}