/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;

/**
 *
 * @author prajeetajoshi
 */
public class CreateEvent extends javax.swing.JFrame {

    /**
     * Creates new form CreateEvent
     */
    public CreateEvent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EventText = new javax.swing.JTextField();
        TimeText = new javax.swing.JTextField();
        DescriptionText = new javax.swing.JTextField();
        GuestText = new javax.swing.JTextField();
        BudgetText = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        SetPriceButton = new javax.swing.JButton();
        TypeText1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/create.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2025-05-22 at 20.45.48.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setText("Create Events");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 328, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 700, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Event Title:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 130, 96, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Event Type:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 188, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setText("Time:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 247, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setText("Description:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel7.setText("Number of Guests:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel8.setText("Budget:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        EventText.setForeground(new java.awt.Color(224, 224, 224));
        EventText.setText("Provide name for the event (e.g. Happy Halloween)");
        EventText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EventTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EventTextFocusLost(evt);
            }
        });
        getContentPane().add(EventText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 124, 450, 40));

        TimeText.setForeground(new java.awt.Color(224, 224, 224));
        TimeText.setText("Choose Time");
        TimeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TimeTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TimeTextFocusLost(evt);
            }
        });
        getContentPane().add(TimeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 242, 40));

        DescriptionText.setForeground(new java.awt.Color(224, 224, 224));
        DescriptionText.setText("Provide short description of event");
        DescriptionText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DescriptionTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DescriptionTextFocusLost(evt);
            }
        });
        getContentPane().add(DescriptionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 298, 440, 50));

        GuestText.setForeground(new java.awt.Color(224, 224, 224));
        GuestText.setText("Provide total attendees");
        GuestText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                GuestTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                GuestTextFocusLost(evt);
            }
        });
        GuestText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuestTextActionPerformed(evt);
            }
        });
        getContentPane().add(GuestText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 140, 40));

        BudgetText.setForeground(new java.awt.Color(224, 224, 224));
        BudgetText.setText("NRs.");
        BudgetText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BudgetTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BudgetTextFocusLost(evt);
            }
        });
        getContentPane().add(BudgetText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 140, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BhirkutiMandap", "Hotel Diyo" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 150, 40));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel9.setText("Date:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2025-06-21", "2025-06-22", "2025-06-23", "2025-06-24" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 180, 40));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel10.setText("Venue:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel11.setText("Event Privacy: ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, -1, -1));

        jRadioButton1.setText("Public");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, -1, -1));

        jRadioButton2.setText("Private");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        jButton1.setBackground(new java.awt.Color(38, 78, 201));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancel");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 100, 40));

        jButton2.setBackground(new java.awt.Color(38, 78, 201));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Edit");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, 100, 40));

        jButton3.setBackground(new java.awt.Color(38, 78, 201));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Confirm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 100, 40));

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel15.setText("Set  Ticket Price: ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, -1, -1));

        SetPriceButton.setText("NRs.");
        getContentPane().add(SetPriceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 150, 40));

        TypeText1.setForeground(new java.awt.Color(224, 224, 224));
        TypeText1.setText("Choose Type");
        TypeText1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TypeText1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TypeText1FocusLost(evt);
            }
        });
        getContentPane().add(TypeText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 182, 140, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/494574320_597322936170871_3710706709161285347_n.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void EventTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EventTextFocusGained
        // TODO add your handling code here:
        if (EventText.getText().equals("Provide name for the event (e.g. Happy Halloween)")){
            EventText.setText("");
            EventText.setForeground(Color.BLACK);
       
        }
    }//GEN-LAST:event_EventTextFocusGained

    private void EventTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EventTextFocusLost
        // TODO add your handling code here:
        if(EventText.getText().isEmpty()){
            EventText.setText("Provide name for the event (e.g. Happy Halloween)");
            EventText.setForeground(new java.awt.Color(216,216,216));
        
           
        } 
    }//GEN-LAST:event_EventTextFocusLost

    private void TimeTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TimeTextFocusGained
        // TODO add your handling code here:
        if ( TimeText.getText().equals("Choose Type")){
             TimeText.setText("");
             TimeText.setForeground(Color.BLACK);
       
        }
        
    }//GEN-LAST:event_TimeTextFocusGained

    private void TimeTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TimeTextFocusLost
        // TODO add your handling code here:
        if( TimeText.getText().isEmpty()){
             TimeText.setText("Choose Type");
             TimeText.setForeground(new java.awt.Color(216,216,216));
        
           
        } 
    }//GEN-LAST:event_TimeTextFocusLost

    private void DescriptionTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DescriptionTextFocusGained
        // TODO add your handling code here:
        if (DescriptionText.getText().equals("Provide short description of event")){
            DescriptionText.setText("");
            DescriptionText.setForeground(Color.BLACK);
       
        }
    }//GEN-LAST:event_DescriptionTextFocusGained

    private void DescriptionTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DescriptionTextFocusLost
        // TODO add your handling code here:
        if(DescriptionText.getText().isEmpty()){
            DescriptionText.setText("Provide short description of event");
            DescriptionText.setForeground(new java.awt.Color(216,216,216));
        
           
        } 
    }//GEN-LAST:event_DescriptionTextFocusLost

    private void GuestTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GuestTextFocusGained
        // TODO add your handling code here:
        if (GuestText.getText().equals("Provide total attendees")){
            GuestText.setText("");
            GuestText.setForeground(Color.BLACK);
       
        }
    }//GEN-LAST:event_GuestTextFocusGained

    private void GuestTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GuestTextFocusLost
        // TODO add your handling code here:
        if(GuestText.getText().isEmpty()){
            GuestText.setText("Provide total attendees");
            GuestText.setForeground(new java.awt.Color(216,216,216));
        
           
        } 
    }//GEN-LAST:event_GuestTextFocusLost

    private void BudgetTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BudgetTextFocusGained
        // TODO add your handling code here:
        if (BudgetText.getText().equals("NRs.")){
            BudgetText.setText("");
            BudgetText.setForeground(Color.BLACK);
       
        }
    }//GEN-LAST:event_BudgetTextFocusGained

    private void BudgetTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BudgetTextFocusLost
        // TODO add your handling code here:
        if(BudgetText.getText().isEmpty()){
            BudgetText.setText("NRs.");
            BudgetText.setForeground(new java.awt.Color(216,216,216));
        
           
        } 
    }//GEN-LAST:event_BudgetTextFocusLost

    private void GuestTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuestTextActionPerformed

    private void TypeText1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TypeText1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeText1FocusGained

    private void TypeText1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TypeText1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeText1FocusLost

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BudgetText;
    private javax.swing.JTextField DescriptionText;
    private javax.swing.JTextField EventText;
    private javax.swing.JTextField GuestText;
    private javax.swing.JButton SetPriceButton;
    private javax.swing.JTextField TimeText;
    private javax.swing.JTextField TypeText1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables

public javax.swing.JTextField getEventText() { return EventText; }
public javax.swing.JTextField getTypeText() { return TimeText; }
public javax.swing.JTextField getDescriptionText() { return DescriptionText; }
public javax.swing.JTextField getGuestText() { return GuestText; }
public javax.swing.JTextField getBudgetText() { return BudgetText; }
public javax.swing.JTextField getTimeText() { return TimeText; }
public javax.swing.JComboBox<String> getDateCombo() { return jComboBox2; }
public javax.swing.JComboBox<String> getVenueCombo() { return jComboBox1; }
public javax.swing.JButton getConfirmButton() { return jButton3; }
public javax.swing.JRadioButton getPublicRadio() { return jRadioButton1; }
public javax.swing.JRadioButton getPrivateRadio() { return jRadioButton2; }
public javax.swing.JButton getTicketPriceButton() { return SetPriceButton; }

    public Object JTextField() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Object getTimeCombo() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


}
