/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;

/**
 *
 * @author prajeetajoshi
 */
public class CustomerEditEvent extends javax.swing.JFrame {

    /**
     * Creates new form CustomerEditEvent
     */
    public CustomerEditEvent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EventText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TypeText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        TimeText = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        DescriptionText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        GuestText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        BudgetText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel7.setText("Description:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2025-05-22 at 20.45.48.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setText("Edit Event");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(299, 299, 299)
                .addComponent(jLabel2)
                .addGap(0, 413, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 918, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Event Title:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 130, 96, -1));

        EventText.setForeground(new java.awt.Color(224, 224, 224));
        EventText.setText("Provide name for the event (e.g. Happy Halloween)");
        EventText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EventTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EventTextFocusLost(evt);
            }
        });
        getContentPane().add(EventText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 124, 569, 40));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Event Type:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 188, -1, -1));

        TypeText.setForeground(new java.awt.Color(224, 224, 224));
        TypeText.setText("Choose Type");
        TypeText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TypeTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TypeTextFocusLost(evt);
            }
        });
        getContentPane().add(TypeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 182, 242, 40));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel9.setText("Date:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 194, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 182, 246, 40));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setText("Time:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 247, -1, -1));

        TimeText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(TimeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 242, 40));

        jLabel6.setText("_");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 271, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 240, 246, 40));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel8.setText("Description:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 298, -1, -1));

        DescriptionText.setForeground(new java.awt.Color(224, 224, 224));
        DescriptionText.setText("Provide short description of event");
        DescriptionText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DescriptionTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DescriptionTextFocusLost(evt);
            }
        });
        getContentPane().add(DescriptionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 298, 569, 59));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel10.setText("Number of Guests:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 382, -1, -1));

        GuestText.setForeground(new java.awt.Color(224, 224, 224));
        GuestText.setText("Provide total attendees");
        GuestText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                GuestTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                GuestTextFocusLost(evt);
            }
        });
        GuestText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuestTextActionPerformed(evt);
            }
        });
        getContentPane().add(GuestText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 376, 246, 40));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel11.setText("Venue:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 375, 245, 40));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel12.setText("Budget:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 454, -1, -1));

        BudgetText.setForeground(new java.awt.Color(224, 224, 224));
        BudgetText.setText("NRs.");
        BudgetText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BudgetTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BudgetTextFocusLost(evt);
            }
        });
        getContentPane().add(BudgetText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 448, 246, 40));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel13.setText("Event Privacy: ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, -1, -1));

        jRadioButton1.setText("Public");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, -1));

        jRadioButton2.setText("Private");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, -1, -1));

        jButton3.setBackground(new java.awt.Color(38, 78, 201));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Confirm");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 547, 100, 40));

        jButton1.setBackground(new java.awt.Color(38, 78, 201));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancel");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 547, 100, 40));

        jButton2.setBackground(new java.awt.Color(38, 78, 201));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Edit");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 547, 100, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerEditEvent.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 920, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EventTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EventTextFocusGained
        // TODO add your handling code here:
        if (EventText.getText().equals("Provide name for the event (e.g. Happy Halloween)")){
            EventText.setText("");
            EventText.setForeground(Color.BLACK); 

        }
    }//GEN-LAST:event_EventTextFocusGained

    private void EventTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EventTextFocusLost
        // TODO add your handling code here:
        if(EventText.getText().isEmpty()){
            EventText.setText("Provide name for the event (e.g. Happy Halloween)");
            EventText.setForeground(new java.awt.Color(216,216,216));

        }
    }//GEN-LAST:event_EventTextFocusLost

    private void TypeTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TypeTextFocusGained
        // TODO add your handling code here:
        if (TypeText.getText().equals("Choose Type")){
            TypeText.setText("");
            TypeText.setForeground(Color.BLACK);

        }

    }//GEN-LAST:event_TypeTextFocusGained

    private void TypeTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TypeTextFocusLost
        // TODO add your handling code here:
        if( TypeText.getText().isEmpty()){
            TypeText.setText("Choose Type");
            TypeText.setForeground(new java.awt.Color(216,216,216));

        }
    }//GEN-LAST:event_TypeTextFocusLost

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void DescriptionTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DescriptionTextFocusGained
        // TODO add your handling code here:
        if (DescriptionText.getText().equals("Provide short description of event")){
            DescriptionText.setText("");
            DescriptionText.setForeground(Color.BLACK);

        }
    }//GEN-LAST:event_DescriptionTextFocusGained

    private void DescriptionTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DescriptionTextFocusLost
        // TODO add your handling code here:
        if(DescriptionText.getText().isEmpty()){
            DescriptionText.setText("Provide short description of event");
            DescriptionText.setForeground(new java.awt.Color(216,216,216));

        }
    }//GEN-LAST:event_DescriptionTextFocusLost

    private void GuestTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GuestTextFocusGained
        // TODO add your handling code here:
        if (GuestText.getText().equals("Provide total attendees")){
            GuestText.setText("");
            GuestText.setForeground(Color.BLACK);

        }
    }//GEN-LAST:event_GuestTextFocusGained

    private void GuestTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GuestTextFocusLost
        // TODO add your handling code here:
        if(GuestText.getText().isEmpty()){
            GuestText.setText("Provide total attendees");
            GuestText.setForeground(new java.awt.Color(216,216,216));

        }
    }//GEN-LAST:event_GuestTextFocusLost

    private void GuestTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuestTextActionPerformed

    private void BudgetTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BudgetTextFocusGained
        // TODO add your handling code here:
        if (BudgetText.getText().equals("NRs.")){
            BudgetText.setText("");
            BudgetText.setForeground(Color.BLACK);

        }
    }//GEN-LAST:event_BudgetTextFocusGained

    private void BudgetTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BudgetTextFocusLost
        // TODO add your handling code here:
        if(BudgetText.getText().isEmpty()){
            BudgetText.setText("NRs.");
            BudgetText.setForeground(new java.awt.Color(216,216,216));

        }
    }//GEN-LAST:event_BudgetTextFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerEditEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerEditEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerEditEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerEditEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerEditEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BudgetText;
    private javax.swing.JTextField DescriptionText;
    private javax.swing.JTextField EventText;
    private javax.swing.JTextField GuestText;
    private javax.swing.JComboBox<String> TimeText;
    private javax.swing.JTextField TypeText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
