/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import Controller.DeleteEventController;
import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import javax.swing.*;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Rashmi Jha
 */

public class DeleteEventView extends javax.swing.JFrame {
    private JDateChooser dateChooser;
    private JTable eventTable;

    /**
     * Creates new form DeleteEvents
     */
    public DeleteEventView() {
        initComponents();
        Type.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{
                    "Cultural Program",
                    "Baby Shower",
                    "Wedding Ceremony",
                    "Reception",
                    "Engagement Party",
                    "Birthday Bash",
                    "Farewell Program",
                    "Anniversary Celebration"
                }
        ));
        dateChooser  = new JDateChooser();
        dateChooser.setDateFormatString("yyyy-MM-dd"); // optional format
       
        getContentPane().add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 185, 150, 30));
       
  
}

          


    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Reason = new javax.swing.JTextField();
        Feedback = new javax.swing.JTextField();
        EventTitle = new javax.swing.JTextField();
        EditeventId = new javax.swing.JTextField();
        Type = new javax.swing.JComboBox<>();
        cancelButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Delete.png"))); // NOI18N
        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Delete Event ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 14, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Edit Event ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 86, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Event Tittle");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 86, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Event Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 77, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Reason for deletion?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 144, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Any feedback for us?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 157, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Are you sure?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 90, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 37, 20));

        jRadioButton1.setText("Yes, I want to delete the event");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        jRadioButton2.setText("No, I don't want to delete th event ");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 216, -1));

        Reason.setForeground(new java.awt.Color(204, 204, 204));
        Reason.setText("Provide short description for the reason to delete event");
        Reason.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ReasonFocusGained(evt);
            }
        });
        getContentPane().add(Reason, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 319, 40));

        Feedback.setForeground(new java.awt.Color(204, 204, 204));
        Feedback.setText("Help us improve by giving feedback");
        Feedback.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FeedbackFocusGained(evt);
            }
        });
        getContentPane().add(Feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 318, 40));

        EventTitle.setForeground(new java.awt.Color(204, 204, 204));
        EventTitle.setText("Provide name for the event(e.g Happy Halloween)");
        EventTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EventTitleFocusGained(evt);
            }
        });
        EventTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EventTitleActionPerformed(evt);
            }
        });
        getContentPane().add(EventTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 319, 30));

        EditeventId.setForeground(new java.awt.Color(204, 204, 204));
        EditeventId.setText("Provide your event id");
        EditeventId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EditeventIdFocusGained(evt);
            }
        });
        getContentPane().add(EditeventId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 319, 30));

        Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });
        getContentPane().add(Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 141, 30));

        cancelButton.setBackground(new java.awt.Color(51, 51, 255));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, 35));

        deleteButton.setBackground(new java.awt.Color(0, 0, 255));
        deleteButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, 35));

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Return to Homepage");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 31, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/logo1.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Backdelete.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 580, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void EventTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EventTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EventTitleActionPerformed

    private void EditeventIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EditeventIdFocusGained
        // TODO add your handling code here:
        if (EditeventId.getText().equals("Provide your event id")) {
            EditeventId.setText("");
            EditeventId.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_EditeventIdFocusGained

    private void EventTitleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EventTitleFocusGained
        // TODO add your handling code here:
        if (EventTitle.getText().equals("Provide name for the event(e.g Happy Halloween)")) {
            EventTitle.setText("");
            EventTitle.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_EventTitleFocusGained

    private void ReasonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ReasonFocusGained
        // TODO add your handling code here:
        if (Reason.getText().equals("Provide short description for the reason to delete event")) {
            Reason.setText("");
            Reason.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_ReasonFocusGained

    private void FeedbackFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FeedbackFocusGained
        // TODO add your handling code here:
        if (Feedback.getText().equals("Help us improve by giving feedback")) {
            Feedback.setText("");
            Feedback.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_FeedbackFocusGained

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_TypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(DeleteEventView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(DeleteEventView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(DeleteEventView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(DeleteEventView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            DeleteEventView deleteEventView = new DeleteEventView();
            DeleteEventController controller = new DeleteEventController(deleteEventView);
            controller.open();

        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EditeventId;
    private javax.swing.JTextField EventTitle;
    private javax.swing.JTextField Feedback;
    private javax.swing.JTextField Reason;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    public void cancelEventListener(ActionListener listener) {
        cancelButton.addActionListener(listener);
    }

    public void deleteEventListener(ActionListener listener) {
        deleteButton.addActionListener(listener);
    }

    public JTextField gettextEditEventId() {  // Add this method
        return EditeventId;
    }

    public JComboBox<String>geteventTypeCombo(){
        return Type;
    }
    public JButton getDeleteButton(){
        return deleteButton;
    }

    public JDateChooser getDateChooser() {
        return dateChooser;
    }
    public boolean isDeletedConfirmed(){
        return jRadioButton1.isSelected();
    }
    public JTextField gettextReason(){
       return Reason;
    }
    public JTextField gettextFeedback(){
        return Feedback;
    }
   
   

}
