/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;

<<<<<<< HEAD
import com.toedter.calendar.JDateChooser;
import controller.EventController;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.PopupMenu;
import javax.swing.*;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import javax.swing.BoxLayout;
import javax.swing.Box;

=======
>>>>>>> origin/forgotpassword
/**
 *
 * @author prasmshachapagain
 */
public class SearchEvent extends javax.swing.JFrame {

<<<<<<< HEAD
    private JDateChooser dateChooser;
    private JTable eventTable;

=======
>>>>>>> origin/forgotpassword
    /**
     * Creates new form SearchEvent
     */
    public SearchEvent() {
        initComponents();
<<<<<<< HEAD
        EvtType.setEnabled(true);
        EvtVenue.setEnabled(true);

       EvtType.setModel(new javax.swing.DefaultComboBoxModel<>(
    new String[] {
        "Pasni", "Bratabandha", "Wedding", "Guniu Cholo", "Concert","Birthday"
    }
));

       EvtVenue.setModel(new javax.swing.DefaultComboBoxModel<>(
    new String[] {
       "Jhapa","Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur", "Chitwan",
    }
));
       dateChooser = new JDateChooser();
       dateChooser.setDateFormatString("yyyy-MM-dd");
       getContentPane().add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 180, 30));

       resultPanel = new JPanel(); 
       resultPanel.setLayout(new GridLayout(0, 1));
       resultPanel.setBounds(80, 430, 420, 150);
       resultPanel.setBackground(Color.WHITE);
       resultPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
       getContentPane().add(resultPanel, new AbsoluteConstraints(80, 430, 420, 300));
        Object popup = null;
       if (popup != null) {
    add((PopupMenu) popup);
} else {
    System.err.println("popup is null!");
}

 


       new EventController(this);
=======
>>>>>>> origin/forgotpassword
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
<<<<<<< HEAD
        searchh = new javax.swing.JButton();
=======
        jButton1 = new javax.swing.JButton();
>>>>>>> origin/forgotpassword
        jLabel2 = new javax.swing.JLabel();
        EvtType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        EvtVenue = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
<<<<<<< HEAD
=======
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
>>>>>>> origin/forgotpassword
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Search Event");
<<<<<<< HEAD
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 160, -1));
=======
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 160, -1));
>>>>>>> origin/forgotpassword

        search.setForeground(new java.awt.Color(204, 204, 204));
        search.setText("search....");
        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 337, 31));

<<<<<<< HEAD
        searchh.setBackground(new java.awt.Color(0, 0, 255));
        searchh.setForeground(new java.awt.Color(255, 255, 255));
        searchh.setText("search");
        getContentPane().add(searchh, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, 31));
=======
        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("search");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, 31));
>>>>>>> origin/forgotpassword

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText(" Event Type:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        EvtType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        EvtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtTypeActionPerformed(evt);
            }
        });
        getContentPane().add(EvtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 263, 31));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setText("Venue:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        EvtVenue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        EvtVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvtVenueActionPerformed(evt);
            }
        });
        getContentPane().add(EvtVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 263, 31));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
<<<<<<< HEAD
        jLabel4.setText("Date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));
=======
        jLabel4.setText("Delete:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 87, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 83, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Filter");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 318, -1, 23));
>>>>>>> origin/forgotpassword

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Return to Homepage");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pinkkkkkk.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 770, 570));
=======
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/pinkkkkkk.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 600, 410));
>>>>>>> origin/forgotpassword

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Screenshot 2025-06-08 at 14.34.16.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchActionPerformed

    private void EvtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EvtTypeActionPerformed

    private void EvtVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvtVenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EvtVenueActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        // TODO add your handling code here:
        if(search.getText().equals("search....")){
            search.setText("");
            search.setForeground(Color.BLACK);      
        }
    }//GEN-LAST:event_searchFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
<<<<<<< HEAD
        public void run() {
            new SearchEvent().setVisible(true);
        }
    });
    }
private JPanel resultPanel;
private JScrollPane resultScrollPane;

=======
            public void run() {
                new SearchEvent().setVisible(true);
            }
        });
    }
>>>>>>> origin/forgotpassword

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EvtType;
    private javax.swing.JComboBox<String> EvtVenue;
<<<<<<< HEAD
    private javax.swing.JButton jButton3;
=======
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
>>>>>>> origin/forgotpassword
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField search;
<<<<<<< HEAD
    private javax.swing.JButton searchh;
    // End of variables declaration//GEN-END:variables


  

    public JComboBox<String> getEventTypeCombo() {
    return EvtType;
}

    public JComboBox<String> getVenueCombo() {
    return EvtVenue;
}

   

   public JButton getSearchButton() {
    return searchh;
}

   


    public JTextField getSearchField() {
       
        return search;
       
    }
    public com.toedter.calendar.JDateChooser getDateChooser() {
    return dateChooser;
}
    public JPanel getResultPanel() {
    return resultPanel;
}

    public JTable getEventTable() {
         return eventTable;
    }
       
}



=======
    // End of variables declaration//GEN-END:variables
}
>>>>>>> origin/forgotpassword
